-- Migration: Insert recruitment notification templates
-- Description: Adds notification templates for recruitment-related emails

-- Application confirmation template
INSERT INTO notification_templates (name, title_template, body_template, subject_template, channel, variables, enabled) VALUES
('job_application_confirmation', 'Application Received for {job_title}', 'Dear {applicant_name},<br><br>Thank you for applying for the position of <strong>{job_title}</strong> at {company_name}.<br><br>We have received your application and our recruitment team will review it shortly. You will be notified about the next steps in the process.<br><br>Application Reference: {application_reference}<br>Applied on: {application_date}<br><br>Best regards,<br>The {company_name} Recruitment Team', 'Application Received for {job_title} - {company_name}', 'email', '["applicant_name", "job_title", "company_name", "application_reference", "application_date"]', TRUE);

-- Application shortlisted template
INSERT INTO notification_templates (name, title_template, body_template, subject_template, channel, variables, enabled) VALUES
('job_application_shortlisted', 'Your Application Has Been Shortlisted', 'Dear {applicant_name},<br><br>We are pleased to inform you that your application for the position of <strong>{job_title}</strong> has been shortlisted.<br><br>We would like to invite you for an interview. Please find the details below:<br><br>Interview Date: {interview_date}<br>Interview Time: {interview_time}<br>Location: {interview_location}<br>Contact Person: {contact_person}<br><br>Please confirm your attendance by replying to this email.<br><br>Best regards,<br>The {company_name} Recruitment Team', 'Application Shortlisted for {job_title} - {company_name}', 'email', '["applicant_name", "job_title", "interview_date", "interview_time", "interview_location", "contact_person", "company_name"]', TRUE);

-- Application rejected template
INSERT INTO notification_templates (name, title_template, body_template, subject_template, channel, variables, enabled) VALUES
('job_application_rejected', 'Update on Your Application Status', 'Dear {applicant_name},<br><br>Thank you for your interest in the position of <strong>{job_title}</strong> at {company_name}.<br><br>After careful consideration of all applications, we regret to inform you that your application has not been successful at this time. We encourage you to apply for other positions that may match your qualifications in the future.<br><br>We appreciate the time you invested in applying and wish you success in your career endeavors.<br><br>Best regards,<br>The {company_name} Recruitment Team', 'Application Update for {job_title} - {company_name}', 'email', '["applicant_name", "job_title", "company_name"]', TRUE);

-- Job offer template
INSERT INTO notification_templates (name, title_template, body_template, subject_template, channel, variables, enabled) VALUES
('job_offer', 'Job Offer for {job_title}', 'Dear {applicant_name},<br><br>We are pleased to offer you the position of <strong>{job_title}</strong> at {company_name}.<br><br>Position Details:<br>Start Date: {start_date}<br>Salary: {salary}<br>Employment Type: {employment_type}<br>Reporting Manager: {reporting_manager}<br><br>Please review the attached offer letter and confirm your acceptance by {acceptance_deadline}.<br><br>We look forward to welcoming you to our team!<br><br>Best regards,<br>{offer_from_name}<br>{offer_from_position}<br>{company_name}', 'Job Offer for {job_title} - {company_name}', 'email', '["applicant_name", "job_title", "company_name", "start_date", "salary", "employment_type", "reporting_manager", "acceptance_deadline", "offer_from_name", "offer_from_position"]', TRUE);

-- Interview reminder template
INSERT INTO notification_templates (name, title_template, body_template, subject_template, channel, variables, enabled) VALUES
('interview_reminder', 'Reminder: Interview for {job_title}', 'Dear {applicant_name},<br><br>This is a reminder about your upcoming interview for the position of <strong>{job_title}</strong>.<br><br>Interview Details:<br>Date: {interview_date}<br>Time: {interview_time}<br>Location: {interview_location}<br>Contact Person: {contact_person}<br><br>Please arrive 10 minutes prior to the scheduled time. If you need to reschedule, please contact us at least 24 hours in advance.<br><br>Best regards,<br>The {company_name} Recruitment Team', 'Interview Reminder for {job_title} - {company_name}', 'email', '["applicant_name", "job_title", "interview_date", "interview_time", "interview_location", "contact_person", "company_name"]', TRUE);

-- Application withdrawn template
INSERT INTO notification_templates (name, title_template, body_template, subject_template, channel, variables, enabled) VALUES
('application_withdrawn_acknowledgment', 'Application Withdrawal Acknowledged', 'Dear {applicant_name},<br><br>We have received your request to withdraw your application for the position of <strong>{job_title}</strong>.<br><br>Your application has been successfully withdrawn from our recruitment process. If you change your mind or wish to apply for other positions, please feel free to do so.<br><br>Thank you for considering {company_name} as a potential employer.<br><br>Best regards,<br>The {company_name} Recruitment Team', 'Application Withdrawal Acknowledged - {company_name}', 'email', '["applicant_name", "job_title", "company_name"]', TRUE);